# Run on every new zsh, interactive or batch

# configs are broken up by file, with .localrc as a per-machine override

#root=..
root=${HOME}

rc_files=(
    zsh/functions
    zsh/config
    zsh/aliases
    .localrc
  )

for rc_file in $rc_files; do
    [[ -f $root/$rc_file ]] && . $root/$rc_file
done
